# -*- coding: utf-8 -*-
"""Webscraper

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iZ73dsIw0mNLM8zPsEb42g5vM2BssfON
"""

!pip install bs4

import pandas as pd
from bs4 import BeautifulSoup
import requests

r = requests.get('https://quotes.toscrape.com/')

b_soup = BeautifulSoup(r.text)

print(b_soup.get_text())

for i in b_soup.findAll("div",{"class":"quote"}):
  print((i.find("span",{"class":"text"})).text)

for i in b_soup.findAll("div",{"class":"quote"}):
  print((i.find("small",{"class":"author"})).text)

for i in b_soup.findAll("div",{"class":"tags"}):
    print((i.find("meta"))['content'])

quotes = []
author= []
tags =[]

for pages in range(1,10):
  f = requests.get('http://quotes.toscrape.com/page/'+str(pages))
  soup = BeautifulSoup(f.text)

for i in soup.findAll("div",{"class":"quote"}):
  quotes.append((i.find("span",{"class":"text"})).text)

for j in soup.findAll("div",{"class":"quote"}):
  author.append((j.find("small",{"class":"author"})).text)

for k in soup.findAll("div",{"class":"tags"}):
  tags.append((k.find("meta"))['content'])

finaldf = pd.DataFrame(
    {'Quotes':quotes,
     'Authors':author,
     'Tags':tags
    })

finaldf